apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.labels }}
  type: NodePort
  ports:
  - port: {{ .Values.containerPort }}
    nodePort: {{ .Values.nodePort }}